from __future__ import annotations

import json
import unittest
import tempfile
from pathlib import Path
from unittest.mock import patch

from tools.mcp_agent_tool import handle_request


def fake_model(system_prompt: str, user_prompt: str) -> str:
    if "Return only valid JSON" in system_prompt:
        return json.dumps(
            {
                "agents": [
                    {
                        "name": "Orchestrator",
                        "purpose": "Plan.",
                        "task": "Plan the workflow.",
                        "input": "User request.",
                    },
                    {
                        "name": "Interface Designer",
                        "purpose": "Design.",
                        "task": "Plan the UI.",
                        "input": "Workflow plan.",
                    },
                    {
                        "name": "Implementation Agent",
                        "purpose": "Build.",
                        "task": "Implement the system.",
                        "input": "Design and plan.",
                    },
                    {
                        "name": "Review Agent",
                        "purpose": "Review.",
                        "task": "Review the output.",
                        "input": "Implementation output.",
                    },
                ]
            }
        )
    return "model output"


def _call_tool(tools: list, name: str, *args: str) -> str:
    for tool in tools or []:
        if getattr(tool, "__name__", "") == name:
            return tool(*args)
    raise AssertionError(f"Missing tool: {name}")


def fake_llama_agent(
    name: str,
    instructions: str,
    input_text: str,
    max_tokens: int,
    tools: list | None = None,
    timeout: int = 120,
) -> str:
    if name == "Orchestrator":
        return json.dumps(
            {
                "project_name": "mcp-project",
                "project_summary": "A tiny Python project generated by MCP.",
                "acceptance_criteria": ["Write a Python file"],
                "agents": [
                    {
                        "name": "Python Engineer",
                        "purpose": "Design the Python file.",
                        "task": "Specify the implementation.",
                        "input": "User request.",
                        "input_format": "Plain text user request.",
                        "expected_output_format": "Python file written through scoped tools.",
                        "logic": "Create a minimal runnable Python file.",
                        "deliverable": "Implementation file.",
                    }
                ],
            }
        )
    if name == "Orchestrator Coordinator":
        for tool in tools or []:
            if getattr(tool, "__name__", "").startswith("run_"):
                tool("Write the Python implementation file.")
        return "Ran Python Engineer."
    if name == "Python Engineer":
        _call_tool(tools or [], "write_file", "app.py", "print('ok')\n")
        return "Created app.py."
    if name == "Project Builder":
        _call_tool(tools or [], "read_file", "app.py")
        return "Inspected app.py."
    if name == "Review Agent":
        return "Generated files were reviewed."
    return f"{name} output"


class McpToolTests(unittest.TestCase):
    def test_tools_list(self) -> None:
        response = handle_request({"jsonrpc": "2.0", "id": 1, "method": "tools/list"})
        self.assertIsNotNone(response)
        names = [tool["name"] for tool in response["result"]["tools"]]
        self.assertIn("design_workflow", names)
        self.assertIn("agent_message", names)
        self.assertIn("framework_profile", names)
        self.assertIn("create_project", names)

    def test_design_workflow_tool(self) -> None:
        response = handle_request(
            {
                "jsonrpc": "2.0",
                "id": 2,
                "method": "tools/call",
                "params": {
                    "name": "design_workflow",
                    "arguments": {"request": "Build a web coding agent dashboard"},
                },
            }
        )
        text = response["result"]["content"][0]["text"]
        payload = json.loads(text)
        self.assertGreaterEqual(len(payload["agents"]), 4)

    def test_framework_profile_tool(self) -> None:
        response = handle_request(
            {
                "jsonrpc": "2.0",
                "id": 3,
                "method": "tools/call",
                "params": {"name": "framework_profile", "arguments": {}},
            }
        )
        text = response["result"]["content"][0]["text"]
        payload = json.loads(text)
        self.assertEqual(payload["recommended"], "llamaindex")
        self.assertTrue(payload["adapter_ready"])

    def test_create_project_tool_writes_files(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            with patch("app.project_runtime.GENERATED_ROOT", Path(temp_dir)):
                with patch("app.project_runtime._run_llama_agent", fake_llama_agent):
                    response = handle_request(
                        {
                            "jsonrpc": "2.0",
                            "id": 4,
                            "method": "tools/call",
                            "params": {
                                "name": "create_project",
                                "arguments": {"request": "Create a tiny Python project"},
                            },
                        }
                    )
            text = response["result"]["content"][0]["text"]
            payload = json.loads(text)
            self.assertEqual(payload["status"], "complete")
            self.assertTrue((Path(payload["project_path"]) / "app.py").exists())


if __name__ == "__main__":
    unittest.main()
