from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed
from collections.abc import Callable
from dataclasses import dataclass
from difflib import SequenceMatcher
from pathlib import Path
from threading import Lock
from typing import Any

from app.llama_runtime import ToolFunction, run_llama_agent
from app.models import Agent, Message, Run, now_iso


PROJECT_ROOT = Path(__file__).resolve().parents[1]
GENERATED_ROOT = PROJECT_ROOT / "generated_projects"
MAX_FILES = 80
MAX_FILE_CHARS = 250_000
MAX_DIRECT_AGENTS = 8
MAX_SUB_ORCHESTRATORS = 4
MAX_TOTAL_SPECIALISTS = 12
PLANNER_TIMEOUT_SECONDS = 180
SUB_ORCHESTRATOR_TIMEOUT_SECONDS = 240
COORDINATOR_TIMEOUT_SECONDS = 900
SPECIALIST_TIMEOUT_SECONDS = 300
BUILDER_TIMEOUT_SECONDS = 420
REVIEW_TIMEOUT_SECONDS = 180

Emitter = Callable[[Message, Agent | None], None]


@dataclass(frozen=True)
class GeneratedFile:
    path: str
    content: str


@dataclass(frozen=True)
class ProjectSpec:
    project_name: str
    files: list[GeneratedFile]
    notes: str = ""


@dataclass(frozen=True)
class PlannedAgent:
    name: str
    purpose: str
    task: str
    input: str
    input_format: str
    expected_output_format: str
    logic: str
    deliverable: str
    depends_on: list[str]


@dataclass(frozen=True)
class PlannedSubOrchestrator:
    name: str
    purpose: str
    domain: str
    task: str
    input: str
    input_format: str
    expected_output_format: str
    logic: str
    deliverable: str


@dataclass(frozen=True)
class WorkflowPlan:
    project_name: str
    project_summary: str
    complexity: str
    estimated_files: int
    requires_sub_orchestrators: bool
    acceptance_criteria: list[str]
    sub_orchestrators: list[PlannedSubOrchestrator]
    agents: list[PlannedAgent]


@dataclass(frozen=True)
class SpecialistResult:
    task_summary: str
    input_format: str
    output_format: str
    logic: str
    files: list[GeneratedFile]
    notes: str = ""


class ProjectRuntimeError(RuntimeError):
    pass


def project_agent_plan(prompt: str) -> list[Agent]:
    target = _slugify(prompt) or "generated-project"
    return [
        Agent(
            name="Orchestrator",
            purpose="Design a request-specific multi-agent workflow.",
            task="Estimate complexity, then assign direct specialists or sub-orchestrators with concrete subtasks.",
            input=prompt,
        ),
        Agent(
            name="Sub-Orchestrators",
            purpose="Optional domain-level planners for larger projects.",
            task="For complex requests, the real run replaces this with frontend, backend, QA, or other domain orchestrators.",
            input="Created only when the root Orchestrator decides the request needs hierarchical planning.",
            input_format="Root workflow plan with domain-specific responsibilities.",
            expected_output_format="Structured JSON with specialist agents for one project domain.",
            logic="Split one domain into implementation, test, design, or documentation specialists.",
        ),
        Agent(
            name="Specialist Agents",
            purpose="Placeholder for the dynamic agents chosen by the orchestrator or sub-orchestrators at runtime.",
            task="The real run replaces this with request-specific agents.",
            input="Generated by the Orchestrator and any sub-orchestrators from the chat request.",
            input_format="Defined by the orchestrator per specialist.",
            expected_output_format="Structured JSON with concrete file contributions.",
            logic="Each real specialist consumes its assigned context and produces a subtask deliverable.",
        ),
        Agent(
            name="Project Builder",
            purpose="Consolidate specialist outputs into a complete file manifest.",
            task="Generate every required source, test, and documentation file.",
            input=f"Project name: {target}. File tools must receive workspace-relative paths only.",
        ),
        Agent(
            name="Verification Agent",
            purpose="Materialize files and verify generated code locally.",
            task="Create the project folder, write files, list artifacts, and run safe verification.",
            input="Generated project files on disk.",
        ),
        Agent(
            name="Review Agent",
            purpose="Review the generated project and report remaining gaps.",
            task="Inspect the generated files and verification result, then produce a final review.",
            input="Written files and verification output.",
        ),
    ]


def run_project_workflow(run: Run, emit: Emitter) -> None:
    GENERATED_ROOT.mkdir(parents=True, exist_ok=True)
    run.status = "planning"

    orchestrator = Agent(
        name="Orchestrator",
        purpose="Design a request-specific multi-agent workflow.",
        task="Assign specialist agents and subtasks from the user's chat request.",
        input=run.prompt,
    )
    run.agents = [orchestrator]
    emit(
        Message(
            sender="Orchestrator",
            recipient="all",
            kind="system",
            content=(
                "Starting a LlamaIndex project-generation workflow. "
                "The orchestrator will design and coordinate specialist coding agents with scoped file tools."
            ),
        )
    )

    _start_agent(orchestrator, emit)
    plan_text = _run_llama_agent(
        orchestrator.name,
        _orchestrator_instructions(),
        f"User request:\n{run.prompt}",
        max_tokens=2600,
        timeout=PLANNER_TIMEOUT_SECONDS,
    )
    plan = parse_workflow_plan(plan_text, run.prompt)
    workspace = ProjectWorkspace(plan.project_name)
    workspace.ensure_created()
    orchestrator.output = f"{_plan_summary(plan)}\n\nProject workspace: {workspace.project_dir}"
    _mark_done(run, orchestrator, emit)

    sub_orchestrator_agents = [_agent_from_sub_orchestrator(item) for item in plan.sub_orchestrators]
    specialist_agents = [_agent_from_plan(agent) for agent in plan.agents]
    for sub_orchestrator in sub_orchestrator_agents:
        sub_orchestrator.depends_on = ["Orchestrator"]
    for specialist in specialist_agents:
        specialist.depends_on = _dedupe_dependencies(["Orchestrator", *specialist.depends_on], specialist.name)
    builder = Agent(
        name="Project Builder",
        purpose="Consolidate all specialist deliverables into a complete source tree.",
        task="Generate every required project file as a JSON file manifest.",
        input=f"Project name: {plan.project_name}. File tools must receive workspace-relative paths only.",
        depends_on=[agent.name for agent in specialist_agents] or [agent.name for agent in sub_orchestrator_agents] or ["Orchestrator"],
    )
    verifier = Agent(
        name="Verification Agent",
        purpose="Materialize files and verify generated code locally.",
        task="Create the project folder, write files, list artifacts, and run safe verification.",
        input="Generated project files on disk.",
        depends_on=["Project Builder"],
    )
    reviewer = Agent(
        name="Review Agent",
        purpose="Review the generated project and report remaining gaps.",
        task="Inspect the generated files and verification result, then produce a final review.",
        input="Written files and verification output.",
        depends_on=["Verification Agent"],
    )
    run.agents = [orchestrator, *sub_orchestrator_agents, *specialist_agents, builder, verifier, reviewer]
    _assign_agent_dag_layers(run.agents)
    if sub_orchestrator_agents:
        emit(
            Message(
                sender="Orchestrator",
                recipient="all",
                kind="system",
                content="Assigned sub-orchestrators: " + ", ".join(agent.name for agent in sub_orchestrator_agents),
            )
        )

    used_specialist_names = {
        "orchestrator",
        "project builder",
        "verification agent",
        "review agent",
        *(agent.name.lower() for agent in sub_orchestrator_agents),
        *(agent.name.lower() for agent in specialist_agents),
    }
    for planned_sub_orchestrator, sub_orchestrator, planned_specialists in _run_sub_orchestrator_dag(
        run.prompt,
        plan,
        sub_orchestrator_agents,
        workspace,
        orchestrator,
        emit,
        used_specialist_names,
    ):
        if len(specialist_agents) + len(planned_specialists) > MAX_TOTAL_SPECIALISTS:
            raise ProjectRuntimeError(
                f"Sub-orchestrators produced too many specialists: "
                f"{len(specialist_agents) + len(planned_specialists)} > {MAX_TOTAL_SPECIALISTS}."
            )
        new_specialists = [_agent_from_plan(agent) for agent in planned_specialists]
        for new_specialist in new_specialists:
            new_specialist.depends_on = _dedupe_dependencies(
                [sub_orchestrator.name, *new_specialist.depends_on],
                new_specialist.name,
            )
        specialist_agents.extend(new_specialists)
        used_specialist_names.update(agent.name.lower() for agent in new_specialists)
        sub_orchestrator.output = _sub_orchestrator_summary(planned_sub_orchestrator, planned_specialists)
        _mark_done(run, sub_orchestrator, emit)

    builder.depends_on = [agent.name for agent in specialist_agents] or [agent.name for agent in sub_orchestrator_agents] or ["Orchestrator"]
    run.agents = [orchestrator, *sub_orchestrator_agents, *specialist_agents, builder, verifier, reviewer]
    _assign_agent_dag_layers(run.agents)
    emit(
        Message(
            sender="Orchestrator",
            recipient="all",
            kind="system",
            content="Assigned dynamic agents: " + ", ".join(agent.name for agent in specialist_agents),
        )
    )

    run.status = "running"
    specialist_outputs: list[str] = []
    execution_summary = _run_specialist_dag(
        run.prompt,
        plan,
        specialist_agents,
        specialist_outputs,
        workspace,
        orchestrator,
        emit,
    )
    orchestrator.output = f"{orchestrator.output}\n\nDAG execution result:\n{execution_summary}"
    emit(Message(sender="Orchestrator", recipient="all", kind="agent", content=execution_summary), orchestrator)

    previous_agent = specialist_agents[-1] if specialist_agents else orchestrator
    _emit_handoff(previous_agent, builder, "Inspect the current project files, resolve gaps, and complete the project.", emit)
    _start_agent(builder, emit)
    builder.output = _run_llama_agent(
        builder.name,
        _builder_instructions(),
        _builder_input(run.prompt, plan, specialist_outputs, workspace),
        tools=_workspace_tools(workspace),
        max_tokens=7000,
        timeout=BUILDER_TIMEOUT_SECONDS,
    )
    _mark_done(run, builder, emit)
    _emit_handoff(builder, verifier, "Verify the generated files from disk.", emit)

    _start_agent(verifier, emit)
    written = workspace.list_files()
    verification = workspace.verify()
    verifier.output = _verification_report(workspace.project_dir, written, verification)
    run.project_path = str(workspace.project_dir)
    run.artifacts = [
        {"name": file_path, "description": str(workspace.project_dir / file_path)}
        for file_path in written
    ]
    _mark_done(run, verifier, emit)
    _emit_handoff(verifier, reviewer, "Review the generated folder and verification output.", emit)

    _start_agent(reviewer, emit)
    reviewer.output = _run_llama_agent(
        reviewer.name,
        _reviewer_instructions(),
        (
            f"User request:\n{run.prompt}\n\n"
            f"Workflow plan:\n{_plan_summary(plan)}\n\n"
            f"Generated project folder:\n{workspace.project_dir}\n\n"
            f"Generated files:\n{json.dumps(written, indent=2)}\n\n"
            f"Verification output:\n{verification}"
        ),
        tools=[_list_files_tool(workspace)],
        max_tokens=1400,
        timeout=REVIEW_TIMEOUT_SECONDS,
    )
    _mark_done(run, reviewer, emit)

    run.status = "complete"
    run.summary = (
        f"Generated project at {workspace.project_dir}. "
        f"Wrote {len(written)} files for request-shaped project '{plan.project_name}'. "
        f"Verification: {_verification_status(verification)}. "
        f"Review: {reviewer.output}"
    )
    emit(Message(sender="Orchestrator", recipient="all", kind="summary", content=run.summary))


def parse_workflow_plan(text: str, prompt: str) -> WorkflowPlan:
    payload = _extract_json_object(text, "Workflow plan")
    project_name = _clean_text(payload.get("project_name")) or _slugify(prompt) or "generated-project"
    project_summary = _clean_text(payload.get("project_summary")) or prompt
    complexity = _clean_complexity(payload.get("complexity"))
    estimated_files = _clean_int(payload.get("estimated_files"), default=0)
    raw_criteria = payload.get("acceptance_criteria", [])
    acceptance_criteria = [str(item).strip() for item in raw_criteria if str(item).strip()] if isinstance(raw_criteria, list) else []
    raw_agents = payload.get("agents", [])
    raw_sub_orchestrators = payload.get("sub_orchestrators", [])
    if not isinstance(raw_agents, list):
        raise ProjectRuntimeError("Orchestrator agents must be a list.")
    if not isinstance(raw_sub_orchestrators, list):
        raise ProjectRuntimeError("Orchestrator sub_orchestrators must be a list.")
    if not raw_agents and not raw_sub_orchestrators:
        raise ProjectRuntimeError("Orchestrator did not return agents or sub_orchestrators.")
    if len(raw_agents) > MAX_DIRECT_AGENTS:
        raise ProjectRuntimeError(f"Orchestrator returned too many direct specialist agents: {len(raw_agents)} > {MAX_DIRECT_AGENTS}.")
    if len(raw_sub_orchestrators) > MAX_SUB_ORCHESTRATORS:
        raise ProjectRuntimeError(
            f"Orchestrator returned too many sub-orchestrators: {len(raw_sub_orchestrators)} > {MAX_SUB_ORCHESTRATORS}."
        )
    requires_sub_orchestrators = bool(payload.get("requires_sub_orchestrators")) or bool(raw_sub_orchestrators)

    used_names = {"orchestrator", "project builder", "verification agent", "review agent"}
    sub_orchestrators = _parse_sub_orchestrators(raw_sub_orchestrators, used_names)
    planned = _parse_planned_agents(raw_agents, "Orchestrator", used_names)

    return WorkflowPlan(
        project_name=_slugify(project_name) or "generated-project",
        project_summary=project_summary,
        complexity=complexity,
        estimated_files=estimated_files,
        requires_sub_orchestrators=requires_sub_orchestrators,
        acceptance_criteria=acceptance_criteria,
        sub_orchestrators=sub_orchestrators,
        agents=planned,
    )


def parse_sub_orchestrator_plan(
    text: str,
    sub_orchestrator_name: str,
    used_names: set[str],
) -> list[PlannedAgent]:
    payload = _extract_json_object(text, f"{sub_orchestrator_name} plan")
    raw_agents = payload.get("agents")
    if not isinstance(raw_agents, list) or not raw_agents:
        raise ProjectRuntimeError(f"{sub_orchestrator_name} did not return a non-empty agents list.")
    if len(raw_agents) > MAX_DIRECT_AGENTS:
        raise ProjectRuntimeError(
            f"{sub_orchestrator_name} returned too many specialists: {len(raw_agents)} > {MAX_DIRECT_AGENTS}."
        )
    return _parse_planned_agents(raw_agents, sub_orchestrator_name, used_names)


def _parse_planned_agents(raw_agents: list[object], label: str, used_names: set[str]) -> list[PlannedAgent]:
    name_map: dict[str, str] = {}
    unique_names: list[str] = []
    for index, raw_agent in enumerate(raw_agents, start=1):
        if not isinstance(raw_agent, dict):
            raise ProjectRuntimeError(f"{label} returned an invalid agent entry.")
        raw_name = _clean_text(raw_agent.get("name")) or f"Specialist {index}"
        unique_name = _unique_agent_name(raw_name, used_names)
        used_names.add(unique_name.lower())
        name_map[raw_name.lower()] = unique_name
        name_map[unique_name.lower()] = unique_name
        unique_names.append(unique_name)

    planned: list[PlannedAgent] = []
    for raw_agent, name in zip(raw_agents, unique_names):
        assert isinstance(raw_agent, dict)
        purpose = _clean_text(raw_agent.get("purpose")) or "Own a specialist project subtask."
        task = _clean_text(raw_agent.get("task")) or purpose
        agent_input = _clean_text(raw_agent.get("input")) or "Use the user request and previous agent outputs."
        input_format = _clean_text(raw_agent.get("input_format")) or (
            "Plain text context containing the user request, workflow plan, and prior specialist outputs."
        )
        expected_output_format = _clean_text(raw_agent.get("expected_output_format")) or (
            "Concrete file changes written through scoped project tools plus a concise summary."
        )
        logic = _clean_text(raw_agent.get("logic")) or (
            "Analyze assigned context, implement the subtask, and return concrete file contributions."
        )
        deliverable = _clean_text(raw_agent.get("deliverable")) or "Concrete implementation guidance for the builder."
        depends_on = _clean_dependency_names(raw_agent.get("depends_on"), name_map)
        planned.append(
            PlannedAgent(
                name=name,
                purpose=purpose,
                task=task,
                input=agent_input,
                input_format=input_format,
                expected_output_format=expected_output_format,
                logic=logic,
                deliverable=deliverable,
                depends_on=depends_on,
            )
        )
    return planned


def _parse_sub_orchestrators(raw_sub_orchestrators: list[object], used_names: set[str]) -> list[PlannedSubOrchestrator]:
    planned: list[PlannedSubOrchestrator] = []
    for index, raw_orchestrator in enumerate(raw_sub_orchestrators, start=1):
        if not isinstance(raw_orchestrator, dict):
            raise ProjectRuntimeError("Orchestrator returned an invalid sub-orchestrator entry.")
        domain = _clean_text(raw_orchestrator.get("domain")) or f"domain-{index}"
        name = _clean_text(raw_orchestrator.get("name")) or f"{domain.title()} Sub-Orchestrator"
        name = _unique_agent_name(name, used_names)
        used_names.add(name.lower())
        purpose = _clean_text(raw_orchestrator.get("purpose")) or f"Plan and coordinate the {domain} domain."
        task = _clean_text(raw_orchestrator.get("task")) or f"Create specialist agents for the {domain} domain."
        agent_input = _clean_text(raw_orchestrator.get("input")) or "Use the root workflow plan and user request."
        input_format = _clean_text(raw_orchestrator.get("input_format")) or (
            "Root workflow plan, domain assignment, acceptance criteria, and user request."
        )
        expected_output_format = _clean_text(raw_orchestrator.get("expected_output_format")) or (
            "JSON object with an agents list. Do not include nested sub_orchestrators."
        )
        logic = _clean_text(raw_orchestrator.get("logic")) or (
            "Split this domain into concrete implementation, testing, design, or documentation specialists."
        )
        deliverable = _clean_text(raw_orchestrator.get("deliverable")) or "Specialist agent plan for this domain."
        planned.append(
            PlannedSubOrchestrator(
                name=name,
                purpose=purpose,
                domain=domain,
                task=task,
                input=agent_input,
                input_format=input_format,
                expected_output_format=expected_output_format,
                logic=logic,
                deliverable=deliverable,
            )
        )
    return planned


def parse_project_spec(text: str, fallback_project_name: str = "generated-project") -> ProjectSpec:
    payload = _extract_json_object(text, "Implementation output")
    project_name = _clean_text(payload.get("project_name")) or fallback_project_name
    files_raw = payload.get("files")
    if not isinstance(files_raw, list) or not files_raw:
        raise ProjectRuntimeError("Project Builder did not return a non-empty files list.")
    if len(files_raw) > MAX_FILES:
        raise ProjectRuntimeError(f"Project Builder returned too many files: {len(files_raw)} > {MAX_FILES}.")

    files: list[GeneratedFile] = []
    for raw_file in files_raw:
        if not isinstance(raw_file, dict):
            raise ProjectRuntimeError("Project Builder returned an invalid file entry.")
        path = _clean_text(raw_file.get("path"))
        content = raw_file.get("content")
        if not path or not isinstance(content, str):
            raise ProjectRuntimeError("Each file entry must include path and string content.")
        if len(content) > MAX_FILE_CHARS:
            raise ProjectRuntimeError(f"{path} is too large.")
        files.append(GeneratedFile(path=path, content=content))

    return ProjectSpec(
        project_name=project_name,
        files=files,
        notes=_clean_text(payload.get("notes")),
    )


def parse_specialist_result(text: str, agent_name: str) -> SpecialistResult:
    payload = _extract_json_object(text, f"{agent_name} output")
    files_raw = payload.get("files", [])
    if not isinstance(files_raw, list):
        raise ProjectRuntimeError(f"{agent_name} output files must be a list.")
    if not files_raw:
        raise ProjectRuntimeError(f"{agent_name} did not contribute any files.")

    files: list[GeneratedFile] = []
    for raw_file in files_raw:
        if not isinstance(raw_file, dict):
            raise ProjectRuntimeError(f"{agent_name} returned an invalid file entry.")
        path = _clean_text(raw_file.get("path"))
        content = raw_file.get("content")
        if not path or not isinstance(content, str):
            raise ProjectRuntimeError(f"{agent_name} file entries require path and string content.")
        if len(content) > MAX_FILE_CHARS:
            raise ProjectRuntimeError(f"{agent_name} file {path} is too large.")
        files.append(GeneratedFile(path=path, content=content))

    return SpecialistResult(
        task_summary=_clean_text(payload.get("task_summary")) or f"{agent_name} completed its assigned task.",
        input_format=_clean_text(payload.get("input_format")),
        output_format=_clean_text(payload.get("output_format")),
        logic=_clean_text(payload.get("logic")),
        files=files,
        notes=_clean_text(payload.get("notes")),
    )


class ProjectWorkspace:
    def __init__(self, requested_name: str) -> None:
        self.name = _slugify(requested_name) or "generated-project"
        self.project_dir = self._unique_project_dir(self.name)
        self._lock = Lock()

    def ensure_created(self) -> None:
        self.project_dir.mkdir(parents=True, exist_ok=True)

    def write_files(self, files: list[GeneratedFile]) -> list[str]:
        self.ensure_created()
        written: list[str] = []
        for file in files:
            written.append(self.write_file(file.path, file.content))
        return written

    def write_file(self, relative_path: str, content: str) -> str:
        if len(content) > MAX_FILE_CHARS:
            raise ProjectRuntimeError(f"{relative_path} is too large.")
        with self._lock:
            destination = self._resolve_file(relative_path)
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_text(content, encoding="utf-8", newline="\n")
            return destination.relative_to(self.project_dir).as_posix()

    def append_file(self, relative_path: str, content: str) -> str:
        if len(content) > MAX_FILE_CHARS:
            raise ProjectRuntimeError(f"{relative_path} append content is too large.")
        with self._lock:
            destination = self._resolve_file(relative_path)
            destination.parent.mkdir(parents=True, exist_ok=True)
            with destination.open("a", encoding="utf-8", newline="\n") as handle:
                handle.write(content)
            return destination.relative_to(self.project_dir).as_posix()

    def read_file(self, relative_path: str) -> str:
        with self._lock:
            source = self._resolve_file(relative_path)
            if not source.exists() or not source.is_file():
                raise ProjectRuntimeError(f"File not found: {relative_path}")
            content = source.read_text(encoding="utf-8")
        if len(content) > MAX_FILE_CHARS:
            raise ProjectRuntimeError(f"{relative_path} is too large to read.")
        return content

    def list_files(self) -> list[str]:
        with self._lock:
            if not self.project_dir.exists():
                return []
            return sorted(
                path.relative_to(self.project_dir).as_posix()
                for path in self.project_dir.rglob("*")
                if path.is_file()
            )

    def verify(self) -> str:
        outputs: list[str] = []
        py_files = sorted(self.project_dir.rglob("*.py"))
        js_files = sorted(self.project_dir.rglob("*.js"))

        if py_files:
            outputs.append(self._run([sys.executable, "-m", "py_compile", *[str(path) for path in py_files]]))
            if (self.project_dir / "tests").exists():
                outputs.append(self._run([sys.executable, "-m", "unittest", "discover", "-s", "tests"]))
        if js_files and shutil.which("node"):
            for path in js_files:
                outputs.append(self._run(["node", "--check", str(path)]))
            if (self.project_dir / "tests").exists():
                outputs.append(self._run(["node", "--test"]))
        if not outputs:
            outputs.append("No Python or JavaScript files found for static verification.")
        return "\n\n".join(outputs)

    def _resolve_file(self, relative_path: str) -> Path:
        raw_path = str(relative_path or "").strip()
        if raw_path.startswith(("/", "\\")) or Path(raw_path).is_absolute() or re.match(r"^[a-zA-Z]:", raw_path):
            raise ProjectRuntimeError(f"Unsafe file path: {relative_path}")
        parts = [
            part
            for part in raw_path.replace("\\", "/").strip("/").split("/")
            if part and part != "."
        ]
        if not parts or any(part == ".." for part in parts):
            raise ProjectRuntimeError(f"Unsafe file path: {relative_path}")
        normalized_parts = self._strip_workspace_prefix(parts)
        if not normalized_parts or any(part == ".." for part in normalized_parts):
            raise ProjectRuntimeError(f"Unsafe file path: {relative_path}")
        normalized = "/".join(normalized_parts)
        destination = (self.project_dir / normalized).resolve()
        try:
            destination.relative_to(self.project_dir.resolve())
        except ValueError as exc:
            raise ProjectRuntimeError(f"Unsafe file path: {relative_path}") from exc
        return destination

    def _strip_workspace_prefix(self, parts: list[str]) -> list[str]:
        normalized = list(parts)
        project_names = {self.name.lower(), self.project_dir.name.lower()}
        generated_root_names = {GENERATED_ROOT.name.lower(), "generated_projects"}
        saw_generated_root = False

        changed = True
        while changed and normalized:
            changed = False
            if normalized and normalized[0].lower() in generated_root_names:
                normalized = normalized[1:]
                changed = True
                saw_generated_root = True
            if normalized and normalized[0].lower() in project_names:
                normalized = normalized[1:]
                changed = True
        if saw_generated_root and len(normalized) > 1 and self._looks_like_project_prefix(normalized[0]):
            normalized = normalized[1:]
        return normalized

    def _looks_like_project_prefix(self, segment: str) -> bool:
        candidate = segment.lower()
        if "." in candidate:
            return False
        reserved_dirs = {"app", "assets", "css", "docs", "js", "public", "scripts", "src", "static", "styles", "tests"}
        if candidate in reserved_dirs:
            return False
        project_names = {self.name.lower(), self.project_dir.name.lower()}
        return any(SequenceMatcher(None, candidate, project_name).ratio() >= 0.82 for project_name in project_names)

    def _run(self, command: list[str]) -> str:
        env = os.environ.copy()
        python_path_entries = [str(self.project_dir), str(self.project_dir / "src")]
        existing_python_path = env.get("PYTHONPATH")
        if existing_python_path:
            python_path_entries.append(existing_python_path)
        env["PYTHONPATH"] = os.pathsep.join(python_path_entries)
        result = subprocess.run(
            command,
            cwd=self.project_dir,
            env=env,
            text=True,
            capture_output=True,
            timeout=30,
            check=False,
        )
        command_text = " ".join(command)
        output = (result.stdout + result.stderr).strip()
        status = "passed" if result.returncode == 0 else f"failed ({result.returncode})"
        return f"$ {command_text}\n{status}\n{output}".strip()

    @staticmethod
    def _unique_project_dir(base_name: str) -> Path:
        candidate = GENERATED_ROOT / base_name
        if not candidate.exists():
            return candidate
        index = 2
        while True:
            candidate = GENERATED_ROOT / f"{base_name}-{index}"
            if not candidate.exists():
                return candidate
            index += 1


def _run_llama_agent(
    name: str,
    instructions: str,
    input_text: str,
    max_tokens: int,
    tools: list[ToolFunction] | None = None,
    timeout: int = 120,
) -> str:
    try:
        return run_llama_agent(
            name=name,
            instructions=instructions,
            input_text=input_text,
            tools=tools or [],
            max_tokens=max_tokens,
            timeout=timeout,
        )
    except Exception as exc:
        raise ProjectRuntimeError(f"{name} failed: {exc}") from exc


def _run_sub_orchestrator_dag(
    user_prompt: str,
    plan: WorkflowPlan,
    sub_orchestrator_agents: list[Agent],
    workspace: ProjectWorkspace,
    orchestrator: Agent,
    emit: Emitter,
    used_names: set[str],
) -> list[tuple[PlannedSubOrchestrator, Agent, list[PlannedAgent]]]:
    if not sub_orchestrator_agents:
        return []

    raw_outputs: dict[str, str] = {}
    with ThreadPoolExecutor(max_workers=len(sub_orchestrator_agents)) as executor:
        futures = {}
        for planned_sub_orchestrator, sub_orchestrator in zip(plan.sub_orchestrators, sub_orchestrator_agents):
            _emit_handoff(orchestrator, sub_orchestrator, f"Plan specialists for domain: {planned_sub_orchestrator.domain}", emit)
            _start_agent(sub_orchestrator, emit)
            future = executor.submit(
                _run_llama_agent,
                sub_orchestrator.name,
                _sub_orchestrator_instructions(planned_sub_orchestrator, plan),
                _sub_orchestrator_input(user_prompt, plan, planned_sub_orchestrator, workspace),
                2400,
                None,
                SUB_ORCHESTRATOR_TIMEOUT_SECONDS,
            )
            futures[future] = sub_orchestrator

        for future in as_completed(futures):
            sub_orchestrator = futures[future]
            try:
                raw_outputs[sub_orchestrator.name] = future.result()
            except Exception:
                sub_orchestrator.status = "failed"
                sub_orchestrator.finished_at = now_iso()
                raise

    planned_results: list[tuple[PlannedSubOrchestrator, Agent, list[PlannedAgent]]] = []
    for planned_sub_orchestrator, sub_orchestrator in zip(plan.sub_orchestrators, sub_orchestrator_agents):
        planned_specialists = parse_sub_orchestrator_plan(
            raw_outputs[sub_orchestrator.name],
            planned_sub_orchestrator.name,
            used_names,
        )
        planned_results.append((planned_sub_orchestrator, sub_orchestrator, planned_specialists))
    return planned_results


def _run_specialist_dag(
    user_prompt: str,
    plan: WorkflowPlan,
    specialist_agents: list[Agent],
    specialist_outputs: list[str],
    workspace: ProjectWorkspace,
    orchestrator: Agent,
    emit: Emitter,
) -> str:
    if not specialist_agents:
        return "No specialist agents were required."

    levels = _agent_execution_levels(specialist_agents)
    agent_by_name = {agent.name: agent for agent in specialist_agents}
    emit_lock = Lock()

    def thread_safe_emit(message: Message, agent: Agent | None = None) -> None:
        with emit_lock:
            emit(message, agent)

    summaries: list[str] = []
    for level_index, level in enumerate(levels, start=1):
        level_names = ", ".join(agent.name for agent in level)
        emit(
            Message(
                sender="Orchestrator",
                recipient="all",
                kind="system",
                content=f"Running DAG level {level_index} in parallel: {level_names}",
            )
        )
        outputs_before_level = list(specialist_outputs)

        def run_one(agent: Agent) -> list[str]:
            local_outputs = list(outputs_before_level)
            before_count = len(local_outputs)
            sender = _dependency_sender(agent, agent_by_name, orchestrator)
            _run_specialist_agent(user_prompt, plan, agent, local_outputs, workspace, sender, thread_safe_emit)
            return local_outputs[before_count:]

        with ThreadPoolExecutor(max_workers=len(level)) as executor:
            futures = {executor.submit(run_one, agent): agent for agent in level}
            level_records: list[str] = []
            for future in as_completed(futures):
                agent = futures[future]
                try:
                    level_records.extend(future.result())
                except Exception:
                    agent.status = "failed"
                    agent.finished_at = now_iso()
                    raise
            specialist_outputs.extend(level_records)
        summaries.append(f"Level {level_index}: {level_names}")

    return "Ran specialist DAG:\n" + "\n".join(f"- {item}" for item in summaries)


def _agent_execution_levels(agents: list[Agent]) -> list[list[Agent]]:
    agent_by_name = {agent.name: agent for agent in agents}
    remaining = set(agent_by_name)
    completed: set[str] = set()
    levels: list[list[Agent]] = []

    while remaining:
        ready_names = sorted(
            name
            for name in remaining
            if all(dependency not in agent_by_name or dependency in completed for dependency in agent_by_name[name].depends_on)
        )
        if not ready_names:
            cycle = ", ".join(sorted(remaining))
            raise ProjectRuntimeError(f"Agent dependency cycle or unsatisfied dependency among: {cycle}")
        levels.append([agent_by_name[name] for name in ready_names])
        completed.update(ready_names)
        remaining.difference_update(ready_names)
    return levels


def _dependency_sender(agent: Agent, agent_by_name: dict[str, Agent], default: Agent) -> Agent:
    for dependency in reversed(agent.depends_on):
        if dependency in agent_by_name:
            return agent_by_name[dependency]
    return default


def _assign_agent_dag_layers(agents: list[Agent]) -> None:
    agent_by_name = {agent.name: agent for agent in agents}
    remaining = set(agent_by_name)
    layer_by_name: dict[str, int] = {}
    current_layer = 0

    while remaining:
        ready_names = sorted(
            name
            for name in remaining
            if all(dependency not in agent_by_name or dependency in layer_by_name for dependency in agent_by_name[name].depends_on)
        )
        if not ready_names:
            for name in sorted(remaining):
                agent_by_name[name].parallel_group = current_layer
            return
        for name in ready_names:
            agent_by_name[name].parallel_group = current_layer
            layer_by_name[name] = current_layer
        remaining.difference_update(ready_names)
        current_layer += 1


def _workspace_tools(workspace: ProjectWorkspace) -> list[ToolFunction]:
    def read_file(path: str) -> str:
        """Read a UTF-8 text file using a path relative to the project root, such as README.md or src/main.py."""
        return workspace.read_file(path)

    def write_file(path: str, content: str) -> str:
        """Create or replace a UTF-8 text file using a project-root-relative path, such as index.html or app.js."""
        written = workspace.write_file(path, content)
        return f"Wrote {written}"

    def append_file(path: str, content: str) -> str:
        """Append UTF-8 text using a project-root-relative path; do not include generated_projects or the project folder."""
        written = workspace.append_file(path, content)
        return f"Appended to {written}"

    def list_files() -> str:
        """List files currently written inside the generated project workspace."""
        files = workspace.list_files()
        return json.dumps(files, indent=2)

    return [read_file, write_file, append_file, list_files]


def _list_files_tool(workspace: ProjectWorkspace) -> ToolFunction:
    def list_files() -> str:
        """List files currently written inside the generated project workspace."""
        return json.dumps(workspace.list_files(), indent=2)

    return list_files


def _specialist_tools(
    user_prompt: str,
    plan: WorkflowPlan,
    specialist_agents: list[Agent],
    specialist_outputs: list[str],
    workspace: ProjectWorkspace,
    sender: Agent,
    emit: Emitter,
) -> list[ToolFunction]:
    tools: list[ToolFunction] = []

    def make_specialist_tool(specialist: Agent) -> ToolFunction:
        def run_specialist(task_brief: str = "") -> str:
            """Run one specialist coding agent and let it write files through scoped project tools."""
            if specialist.status == "done":
                return specialist.output or f"{specialist.name} already completed."
            return _run_specialist_agent(
                user_prompt,
                plan,
                specialist,
                specialist_outputs,
                workspace,
                sender,
                emit,
                task_brief,
            )

        run_specialist.__name__ = _tool_name(f"run_{specialist.name}")
        run_specialist.__doc__ = (
            f"Run {_clean_text(specialist.name)}. Purpose: {specialist.purpose}. "
            f"Task: {specialist.task}. Use this to delegate real coding work to that specialist."
        )
        return run_specialist

    for specialist in specialist_agents:
        tools.append(make_specialist_tool(specialist))
    return tools


def _run_specialist_agent(
    user_prompt: str,
    plan: WorkflowPlan,
    specialist: Agent,
    specialist_outputs: list[str],
    workspace: ProjectWorkspace,
    sender: Agent,
    emit: Emitter,
    task_brief: str = "",
) -> str:
    _emit_handoff(sender, specialist, task_brief or f"Own this subtask: {specialist.task}", emit)
    _start_agent(specialist, emit)
    raw_output = _run_llama_agent(
        specialist.name,
        _specialist_instructions(specialist, plan),
        _specialist_input(user_prompt, plan, specialist_outputs, specialist, workspace, task_brief),
        tools=_workspace_tools(workspace),
        max_tokens=4500,
        timeout=SPECIALIST_TIMEOUT_SECONDS,
    )
    files = workspace.list_files()
    specialist.output = _workspace_agent_summary(raw_output, files)
    specialist_outputs.append(
        json.dumps(
            {
                "agent": specialist.name,
                "task": specialist.task,
                "input_format": specialist.input_format,
                "expected_output_format": specialist.expected_output_format,
                "logic": specialist.logic,
                "output": raw_output,
                "files_after_agent": files,
            },
            indent=2,
        )
    )
    _mark_done(None, specialist, emit)
    return specialist.output


def _agent_from_plan(agent: PlannedAgent) -> Agent:
    return Agent(
        name=agent.name,
        purpose=agent.purpose,
        task=agent.task,
        input=agent.input,
        input_format=agent.input_format,
        expected_output_format=agent.expected_output_format,
        logic=agent.logic,
        deliverable=agent.deliverable,
        depends_on=list(agent.depends_on),
    )


def _agent_from_sub_orchestrator(agent: PlannedSubOrchestrator) -> Agent:
    return Agent(
        name=agent.name,
        purpose=f"{agent.purpose} Domain: {agent.domain}.",
        task=agent.task,
        input=agent.input,
        input_format=agent.input_format,
        expected_output_format=agent.expected_output_format,
        logic=agent.logic,
        deliverable=agent.deliverable,
    )


def _mark_done(run: Run | None, agent: Agent, emit: Emitter) -> None:
    if agent.started_at is None:
        agent.started_at = now_iso()
    agent.status = "done"
    agent.finished_at = now_iso()
    emit(Message(sender=agent.name, recipient="all", kind="agent", content=agent.output), agent)


def _start_agent(agent: Agent, emit: Emitter) -> None:
    agent.status = "running"
    agent.started_at = now_iso()
    emit(Message(sender=agent.name, recipient="Orchestrator", kind="status", content=f"Starting: {agent.task}"), agent)


def _emit_handoff(sender: Agent, recipient: Agent, content: str, emit: Emitter) -> None:
    message = Message(sender=sender.name, recipient=recipient.name, kind="handoff", content=content)
    sender.messages.append(message)
    recipient.messages.append(message)
    emit(message, sender)


def _verification_report(project_dir: Path, written: list[str], verification: str) -> str:
    file_list = "\n".join(f"- {path}" for path in written)
    return f"Created project folder: {project_dir}\n\nFiles:\n{file_list}\n\nVerification:\n{verification}"


def _verification_status(verification: str) -> str:
    return "passed" if "failed (" not in verification.lower() else "failed"


def _plan_summary(plan: WorkflowPlan) -> str:
    criteria = "\n".join(f"- {item}" for item in plan.acceptance_criteria) or "- Build a working project matching the request."
    sub_orchestrators = "\n".join(
        (
            f"- {agent.name} ({agent.domain}): {agent.task}\n"
            f"  Logic: {agent.logic}\n"
            f"  Deliverable: {agent.deliverable}"
        )
        for agent in plan.sub_orchestrators
    ) or "- None"
    agents = "\n".join(
        (
            f"- {agent.name}: {agent.task}\n"
            f"  Input format: {agent.input_format}\n"
            f"  Expected output: {agent.expected_output_format}\n"
            f"  Depends on: {', '.join(agent.depends_on) if agent.depends_on else 'none'}\n"
            f"  Logic: {agent.logic}\n"
            f"  Deliverable: {agent.deliverable}"
        )
        for agent in plan.agents
    ) or "- None; specialists will be planned by sub-orchestrators."
    return (
        f"Project: {plan.project_name}\n"
        f"Summary: {plan.project_summary}\n"
        f"Complexity: {plan.complexity}\n"
        f"Estimated files: {plan.estimated_files or 'unknown'}\n"
        f"Requires sub-orchestrators: {plan.requires_sub_orchestrators}\n"
        f"Acceptance criteria:\n{criteria}\n"
        f"Sub-orchestrators:\n{sub_orchestrators}\n"
        f"Assigned agents:\n{agents}"
    )


def _orchestrator_instructions() -> str:
    return (
        "You are the lead orchestrator in a real coding-agent workflow. "
        "Read the user's request, estimate project complexity, and design a project-specific agent pipeline. "
        "Return only valid JSON, no markdown fences. Schema: "
        '{"project_name":"short-kebab-name","project_summary":"what will be built",'
        '"complexity":"small|medium|large","estimated_files":8,'
        '"requires_sub_orchestrators":false,'
        '"acceptance_criteria":["criterion"],'
        '"sub_orchestrators":[{"name":"Frontend Sub-Orchestrator","domain":"frontend",'
        '"purpose":"why this sub-orchestrator exists","task":"specific domain planning task",'
        '"input":"domain context it receives","input_format":"specific input shape",'
        '"expected_output_format":"JSON with agents list only","logic":"how it splits the domain",'
        '"deliverable":"specialist plan for this domain"}],'
        '"agents":[{"name":"Role name","purpose":"why this agent exists",'
        '"task":"specific subtask assigned by orchestrator","input":"context it receives",'
        '"input_format":"specific structure/context this agent will receive",'
        '"expected_output_format":"specific JSON/files/spec this agent must return",'
        '"logic":"step-by-step logic this agent should follow",'
        '"deliverable":"what this agent must hand to the builder",'
        '"depends_on":["Other specialist name"]}]}. '
        "For small and medium tasks, set requires_sub_orchestrators=false and create 2 to 6 direct specialist agents. "
        "For large, multi-domain, or high-file-count tasks, set requires_sub_orchestrators=true and create 1 to 4 sub-orchestrators. "
        "When using sub-orchestrators, direct agents may be empty or limited to cross-cutting specialists. "
        "Every specialist must have a concrete coding, test, UI, data, or documentation subtask. "
        "Be specific about input format, expected output format, and logic for each agent. "
        "Set depends_on to only the specialist agent names that must complete before this agent can run. "
        "Use an empty depends_on list when an agent can run in parallel with other independent agents. "
        "Assign at least one specialist that writes implementation files and at least one that owns verification, tests, or review artifacts. "
        "For web apps, include product/UX/frontend/backend/test roles as needed. "
        "For CLIs, include CLI/API/test/docs roles. For data tools, include schema/parser/analysis/test roles. "
        "For browser games, split gameplay logic, UI/rendering, styling, and quality/testing responsibilities. "
        "Do not include Orchestrator, Project Builder, Verification Agent, or Review Agent in the agents list. "
        "Do not ask sub-orchestrators to create more sub-orchestrators; max hierarchy depth is 2."
    )


def _sub_orchestrator_instructions(sub_orchestrator: PlannedSubOrchestrator, plan: WorkflowPlan) -> str:
    criteria = "; ".join(plan.acceptance_criteria) or "match the user's request"
    return (
        f"You are {sub_orchestrator.name}, a domain sub-orchestrator for {sub_orchestrator.domain}. "
        f"Purpose: {sub_orchestrator.purpose}. "
        f"Task: {sub_orchestrator.task}. "
        f"Required logic: {sub_orchestrator.logic}. "
        f"Project acceptance criteria: {criteria}. "
        "Return only valid JSON, no markdown fences. Schema: "
        '{"agents":[{"name":"Specialist name","purpose":"why this agent exists",'
        '"task":"specific domain subtask","input":"context it receives",'
        '"input_format":"specific context shape","expected_output_format":"files or summary it must produce",'
        '"logic":"step-by-step logic","deliverable":"what this specialist must create",'
        '"depends_on":["Other specialist name"]}]}. '
        "Create 1 to 6 concrete specialist agents for your assigned domain only. "
        "Set depends_on to only the specialist names in this domain that must finish first; use [] for parallelizable work. "
        "Do not create nested sub-orchestrators. Do not include Orchestrator, Project Builder, Verification Agent, or Review Agent."
    )


def _sub_orchestrator_input(
    user_prompt: str,
    plan: WorkflowPlan,
    sub_orchestrator: PlannedSubOrchestrator,
    workspace: ProjectWorkspace,
) -> str:
    return (
        f"Original user request:\n{user_prompt}\n\n"
        f"Root workflow plan:\n{_plan_summary(plan)}\n\n"
        f"{_workspace_tool_context(workspace)}\n\n"
        f"Your domain: {sub_orchestrator.domain}\n"
        f"Your assigned input:\n{sub_orchestrator.input}\n\n"
        "Create specialist agents for this domain now."
    )


def _sub_orchestrator_summary(sub_orchestrator: PlannedSubOrchestrator, specialists: list[PlannedAgent]) -> str:
    specialist_list = "\n".join(
        (
            f"- {agent.name}: {agent.task}\n"
            f"  Depends on: {', '.join(agent.depends_on) if agent.depends_on else 'none'}"
        )
        for agent in specialists
    ) or "- No specialists planned."
    return (
        f"Domain: {sub_orchestrator.domain}\n"
        f"Complexity handled by sub-orchestrator: {sub_orchestrator.logic}\n\n"
        f"Specialists planned:\n{specialist_list}"
    )


def _coordinator_instructions(plan: WorkflowPlan) -> str:
    return (
        "You are the LlamaIndex orchestrator coordinator. You have one tool per specialist agent. "
        "Call every specialist tool exactly once unless a specialist is clearly irrelevant to the plan. "
        "Pass each specialist concrete instructions that reference its assigned task and the project acceptance criteria. "
        "Do not write project files yourself. Your job is to distribute the work, sequence specialists, and report what each completed. "
        f"Project summary: {plan.project_summary}"
    )


def _coordinator_input(user_prompt: str, plan: WorkflowPlan, workspace: ProjectWorkspace) -> str:
    return (
        f"Original user request:\n{user_prompt}\n\n"
        f"Workflow plan:\n{_plan_summary(plan)}\n\n"
        f"{_workspace_tool_context(workspace)}\n\n"
        "Coordinate the specialist agents now. Each specialist must produce real files through its scoped tools."
    )


def _specialist_instructions(agent: Agent, plan: WorkflowPlan) -> str:
    criteria = "; ".join(plan.acceptance_criteria) or "match the user's request"
    return (
        f"You are {agent.name}, a specialist agent in a multi-agent project build. "
        f"Purpose: {agent.purpose}. "
        f"Own only your assigned subtask: {agent.task}. "
        f"Input format you were promised: {agent.input_format}. "
        f"Expected output format: {agent.expected_output_format}. "
        f"Required logic: {agent.logic}. "
        f"Acceptance criteria: {criteria}. "
        "You have scoped project-file tools. Use them to read, write, append, and list files in the generated project workspace. "
        "Tool path rule: pass only paths relative to the workspace root, like index.html, app.js, src/main.py, or README.md. "
        "Never include generated_projects/, the project folder name, absolute paths, or parent-directory traversal in tool paths. "
        "Actually do your part of the coding by writing concrete source, test, style, markup, data, or documentation files. "
        "If your role is design or QA, write useful project files such as README sections, TESTING.md, tests, fixtures, or review notes. "
        "For browser games, do not stop at a mockup: write executable HTML/CSS/JavaScript with gameplay state, input handling, win/draw logic, and reset behavior. "
        "After using tools, return a concise summary of files changed, logic implemented, and any remaining risks."
    )


def _specialist_input(
    user_prompt: str,
    plan: WorkflowPlan,
    previous_outputs: list[str],
    agent: Agent,
    workspace: ProjectWorkspace,
    task_brief: str = "",
) -> str:
    previous = "\n\n".join(previous_outputs) if previous_outputs else "No previous specialist output yet."
    return (
        f"Original user request:\n{user_prompt}\n\n"
        f"Project plan:\n{_plan_summary(plan)}\n\n"
        f"{_workspace_tool_context(workspace)}\n\n"
        f"Coordinator task brief:\n{task_brief or agent.task}\n\n"
        f"Your assigned input:\n{agent.input}\n\n"
        f"Your input format:\n{agent.input_format}\n\n"
        f"Your expected output format:\n{agent.expected_output_format}\n\n"
        f"Your logic:\n{agent.logic}\n\n"
        f"Previous specialist outputs:\n{previous}"
    )


def _builder_instructions() -> str:
    return (
        "You are the Project Builder. Inspect the files already written by specialist agents, then use scoped file tools to complete the project. "
        "Rules: merge and normalize specialist work; include README.md; include tests or test notes when relevant; use only workspace-relative tool paths "
        "such as index.html, app.js, src/main.py, or README.md; do not include generated_projects/, the project folder name, absolute paths, "
        "or parent-directory traversal; and do not omit required source code. "
        "Honor the requested project type and stack. Prefer self-contained projects that can be verified without installs. "
        "For Python projects, prefer stdlib and unittest. For JavaScript projects, prefer Node built-ins. "
        "For browser apps and browser games, static HTML/CSS/JS is acceptable unless the user asks for a framework. "
        "After using tools, return a concise build summary with the files completed and any gaps."
    )


def _builder_input(
    user_prompt: str,
    plan: WorkflowPlan,
    specialist_outputs: list[str],
    workspace: ProjectWorkspace,
) -> str:
    outputs = "\n\n---\n\n".join(specialist_outputs)
    return (
        f"Original user request:\n{user_prompt}\n\n"
        f"Workflow plan:\n{_plan_summary(plan)}\n\n"
        f"{_workspace_tool_context(workspace)}\n\n"
        f"Current files:\n{json.dumps(workspace.list_files(), indent=2)}\n\n"
        f"Specialist structured outputs:\n{outputs}\n\n"
        "Inspect the current file tree, preserve useful specialist code and docs, resolve gaps, and finish the project files now."
    )


def _workspace_tool_context(workspace: ProjectWorkspace) -> str:
    return (
        f"Generated project workspace on disk: {workspace.project_dir}\n"
        "File tools are already scoped to this folder. Tool path arguments must be relative to the workspace root, "
        "for example index.html, app.js, src/main.py, tests/test_app.py, or README.md. "
        "Do not prefix tool paths with generated_projects/ or the project folder name."
    )


def _specialist_result_to_dict(result: SpecialistResult) -> dict[str, Any]:
    return {
        "task_summary": result.task_summary,
        "input_format": result.input_format,
        "output_format": result.output_format,
        "logic": result.logic,
        "files": [{"path": file.path, "content": file.content} for file in result.files],
        "notes": result.notes,
    }


def _specialist_output_summary(agent: Agent, result: SpecialistResult) -> str:
    file_list = "\n".join(f"- {file.path}" for file in result.files)
    return (
        f"Task summary: {result.task_summary}\n\n"
        f"Input format consumed: {result.input_format or agent.input_format}\n\n"
        f"Output format produced: {result.output_format or agent.expected_output_format}\n\n"
        f"Logic applied: {result.logic or agent.logic}\n\n"
        f"File contributions:\n{file_list}\n\n"
        f"Notes: {result.notes}"
    )


def _workspace_agent_summary(output: str, files: list[str]) -> str:
    file_list = "\n".join(f"- {path}" for path in files) or "- No files written yet."
    return f"{output}\n\nWorkspace files after this agent:\n{file_list}"


def _reviewer_instructions() -> str:
    return (
        "You are the review agent. Review the generated project from the artifact list and verification output. "
        "State what was created, whether verification passed, and the top issues or next steps. "
        "Be concise and do not claim manual inspection beyond the provided evidence."
    )


def _extract_json_object(text: str, label: str) -> dict[str, Any]:
    cleaned = text.strip()
    if cleaned.startswith("```"):
        cleaned = re.sub(r"^```(?:json)?\s*", "", cleaned)
        cleaned = re.sub(r"\s*```$", "", cleaned)
    try:
        payload = json.loads(cleaned)
    except json.JSONDecodeError:
        match = re.search(r"\{.*\}", cleaned, re.DOTALL)
        if not match:
            raise ProjectRuntimeError(f"{label} did not contain JSON.") from None
        try:
            payload = json.loads(match.group(0))
        except json.JSONDecodeError as exc:
            raise ProjectRuntimeError(f"{label} JSON was malformed.") from exc
    if not isinstance(payload, dict):
        raise ProjectRuntimeError(f"{label} JSON must be an object.")
    return payload


def _slugify(value: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9]+", "-", value.lower()).strip("-")
    return slug[:48].strip("-")


def _tool_name(value: str) -> str:
    name = re.sub(r"[^a-zA-Z0-9_]+", "_", value.lower()).strip("_")
    if not name:
        name = "run_specialist"
    if not name[0].isalpha():
        name = f"tool_{name}"
    return name[:64]


def _clean_text(value: object) -> str:
    return str(value or "").strip()


def _clean_complexity(value: object) -> str:
    text = _clean_text(value).lower()
    return text if text in {"small", "medium", "large"} else "medium"


def _clean_int(value: object, default: int = 0) -> int:
    try:
        number = int(value)
    except (TypeError, ValueError):
        return default
    return max(0, number)


def _clean_dependency_names(value: object, name_map: dict[str, str]) -> list[str]:
    if not isinstance(value, list):
        return []
    dependencies: list[str] = []
    for item in value:
        dependency = _clean_text(item)
        if not dependency:
            continue
        dependencies.append(name_map.get(dependency.lower(), dependency))
    return _dedupe_dependencies(dependencies, self_name="")


def _dedupe_dependencies(dependencies: list[str], self_name: str) -> list[str]:
    clean: list[str] = []
    seen: set[str] = set()
    self_key = self_name.lower()
    for dependency in dependencies:
        name = _clean_text(dependency)
        key = name.lower()
        if not name or key == self_key or key in seen:
            continue
        clean.append(name)
        seen.add(key)
    return clean


def _unique_agent_name(name: str, used_names: set[str]) -> str:
    base = re.sub(r"\s+", " ", name).strip() or "Specialist"
    if base.lower() not in used_names:
        return base[:60]
    index = 2
    while f"{base} {index}".lower() in used_names:
        index += 1
    return f"{base} {index}"[:60]

